//! How to start a server, uniformly across loaders.
//!
//! The conditionals everyone else ends up with — `if fabric { classpath } else { run.sh }`
//! sprayed through launch, update and cleanup — come from abstracting *installation*. We
//! abstract the **result** instead: every loader produces a `LaunchProfile`, and only two
//! places in the codebase ever match on its variants.
//!
//! A side benefit worth having: because we reconstruct what Forge and NeoForge's `run.sh` does
//! rather than shelling out to it, the server starts under the JVM hopper provisioned. `run.sh`
//! hardcodes a bare `java` and cannot.

use serde::{Deserialize, Serialize};

use crate::model::RelPath;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum LaunchProfile {
    /// We own the whole command line: Fabric and vanilla.
    Classpath {
        main_class: String,
        /// Ordered; classpath order is significant to the JVM.
        classpath: Vec<RelPath>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        jvm_args: Vec<String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        program_args: Vec<String>,
    },
    /// A single runnable jar: Quilt, and Forge before 1.17.
    ExecutableJar {
        jar: RelPath,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        jvm_args: Vec<String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        program_args: Vec<String>,
    },
    /// Forge 1.17+ and NeoForge, which ship `@`-argfiles instead of a jar.
    ArgFiles {
        /// Generated by the installer and referenced with `@`.
        module_argfile_unix: RelPath,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        module_argfile_windows: Option<RelPath>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        program_args: Vec<String>,
    },
}

/// Arguments for `java`, in order, given a JVM and the operator's own flags.
///
/// This and the start-script renderer are the only two places that match on `LaunchProfile`.
impl LaunchProfile {
    pub fn command_args(&self, jvm_args_file: Option<&RelPath>, windows: bool) -> Vec<String> {
        let mut out = Vec::new();

        // The operator's flags come first so they can influence everything after.
        if let Some(f) = jvm_args_file {
            out.push(format!("@{f}"));
        }

        match self {
            Self::Classpath {
                main_class,
                classpath,
                jvm_args,
                program_args,
            } => {
                out.extend(jvm_args.iter().cloned());
                if !classpath.is_empty() {
                    let sep = if windows { ";" } else { ":" };
                    let joined = classpath
                        .iter()
                        .map(RelPath::as_str)
                        .collect::<Vec<_>>()
                        .join(sep);
                    out.push("-cp".into());
                    out.push(joined);
                }
                out.push(main_class.clone());
                out.extend(program_args.iter().cloned());
            }
            Self::ExecutableJar {
                jar,
                jvm_args,
                program_args,
            } => {
                out.extend(jvm_args.iter().cloned());
                out.push("-jar".into());
                out.push(jar.as_str().to_owned());
                out.extend(program_args.iter().cloned());
            }
            Self::ArgFiles {
                module_argfile_unix,
                module_argfile_windows,
                program_args,
            } => {
                let f = if windows {
                    module_argfile_windows
                        .as_ref()
                        .unwrap_or(module_argfile_unix)
                } else {
                    module_argfile_unix
                };
                out.push(format!("@{f}"));
                out.extend(program_args.iter().cloned());
            }
        }
        out
    }

    /// Files that must exist for this profile to start. Used to verify an install.
    pub fn required_files(&self) -> Vec<&RelPath> {
        match self {
            Self::Classpath { classpath, .. } => classpath.iter().collect(),
            Self::ExecutableJar { jar, .. } => vec![jar],
            Self::ArgFiles {
                module_argfile_unix,
                module_argfile_windows,
                ..
            } => {
                let mut v = vec![module_argfile_unix];
                v.extend(module_argfile_windows.iter());
                v
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn p(s: &str) -> RelPath {
        RelPath::parse(s).unwrap()
    }

    fn fabric() -> LaunchProfile {
        LaunchProfile::Classpath {
            main_class: "net.fabricmc.loader.impl.launch.knot.KnotServer".into(),
            classpath: vec![
                p("libraries/net/fabricmc/fabric-loader.jar"),
                p("server.jar"),
            ],
            jvm_args: vec![],
            program_args: vec!["nogui".into()],
        }
    }

    #[test]
    fn fabric_becomes_a_classpath_invocation() {
        let args = fabric().command_args(None, false);
        assert_eq!(args[0], "-cp");
        assert_eq!(
            args[1],
            "libraries/net/fabricmc/fabric-loader.jar:server.jar"
        );
        assert_eq!(args[2], "net.fabricmc.loader.impl.launch.knot.KnotServer");
        assert_eq!(args[3], "nogui");
    }

    #[test]
    fn classpath_separator_is_platform_specific() {
        assert!(fabric().command_args(None, true)[1].contains(';'));
        assert!(fabric().command_args(None, false)[1].contains(':'));
    }

    #[test]
    fn classpath_order_is_preserved() {
        // The JVM resolves classes in classpath order, so reordering changes behaviour.
        let args = fabric().command_args(None, false);
        let cp = &args[1];
        assert!(cp.find("fabric-loader").unwrap() < cp.find("server.jar").unwrap());
    }

    #[test]
    fn neoforge_becomes_an_argfile_invocation() {
        let profile = LaunchProfile::ArgFiles {
            module_argfile_unix: p("libraries/net/neoforged/neoforge/21.1.95/unix_args.txt"),
            module_argfile_windows: Some(p(
                "libraries/net/neoforged/neoforge/21.1.95/win_args.txt",
            )),
            program_args: vec!["nogui".into()],
        };
        let unix = profile.command_args(None, false);
        assert_eq!(
            unix[0],
            "@libraries/net/neoforged/neoforge/21.1.95/unix_args.txt"
        );
        let win = profile.command_args(None, true);
        assert!(win[0].ends_with("win_args.txt"));
    }

    #[test]
    fn argfiles_fall_back_to_unix_when_no_windows_file_exists() {
        let profile = LaunchProfile::ArgFiles {
            module_argfile_unix: p("libraries/args.txt"),
            module_argfile_windows: None,
            program_args: vec![],
        };
        assert_eq!(profile.command_args(None, true)[0], "@libraries/args.txt");
    }

    #[test]
    fn quilt_becomes_a_jar_invocation() {
        let profile = LaunchProfile::ExecutableJar {
            jar: p("quilt-server-launch.jar"),
            jvm_args: vec![],
            program_args: vec!["nogui".into()],
        };
        let args = profile.command_args(None, false);
        assert_eq!(args, ["-jar", "quilt-server-launch.jar", "nogui"]);
    }

    #[test]
    fn the_operators_jvm_args_file_comes_first_for_every_loader() {
        // jvm.args is the single uniform knob, so it must apply regardless of loader shape.
        let args_file = p("jvm.args");
        for profile in [
            fabric(),
            LaunchProfile::ExecutableJar {
                jar: p("a.jar"),
                jvm_args: vec![],
                program_args: vec![],
            },
            LaunchProfile::ArgFiles {
                module_argfile_unix: p("x.txt"),
                module_argfile_windows: None,
                program_args: vec![],
            },
        ] {
            assert_eq!(
                profile.command_args(Some(&args_file), false)[0],
                "@jvm.args",
                "{profile:?}"
            );
        }
    }

    #[test]
    fn required_files_lists_what_must_exist_to_start() {
        assert_eq!(fabric().required_files().len(), 2);
        let neo = LaunchProfile::ArgFiles {
            module_argfile_unix: p("a.txt"),
            module_argfile_windows: Some(p("b.txt")),
            program_args: vec![],
        };
        assert_eq!(neo.required_files().len(), 2);
    }

    #[test]
    fn profiles_round_trip_through_the_lockfile() {
        // Stored in the lockfile so `hopper status` and the start script never re-derive it or
        // touch the network.
        for profile in [
            fabric(),
            LaunchProfile::ExecutableJar {
                jar: p("q.jar"),
                jvm_args: vec!["-Xmx4G".into()],
                program_args: vec!["nogui".into()],
            },
            LaunchProfile::ArgFiles {
                module_argfile_unix: p("u.txt"),
                module_argfile_windows: None,
                program_args: vec![],
            },
        ] {
            let json = serde_json::to_string(&profile).unwrap();
            assert_eq!(
                serde_json::from_str::<LaunchProfile>(&json).unwrap(),
                profile
            );
        }
    }
}
