//! systemd **user** units for a server directory: the server itself, and optionally a timer
//! that keeps its pack up to date.
//!
//! User units because they need no root and touch nothing outside the operator's home. They
//! run at boot only with lingering enabled (`loginctl enable-linger`), which the caller checks
//! and explains.
//!
//! Rendering is pure; writing the files and talking to `systemctl` is the binary's job.

use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum UnitError {
    #[error("{0:?} cannot be used in a systemd unit (it contains a control character)")]
    UnsafePath(String),
    #[error("no usable unit name can be made from {0:?}; pass --name")]
    BadName(String),
    #[error(
        "unknown update schedule {0:?}; use off, hourly, daily, weekly or an OnCalendar expression"
    )]
    BadSchedule(String),
}

/// When the update timer fires.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Schedule {
    Hourly,
    Daily,
    Weekly,
    /// A systemd `OnCalendar=` expression, e.g. `Mon *-*-* 04:00`. Validated by the caller
    /// with `systemd-analyze calendar`, since only systemd knows its own grammar.
    Calendar(String),
}

impl Schedule {
    /// `off` (or `none`) is no schedule at all.
    pub fn parse(s: &str) -> Result<Option<Self>, UnitError> {
        Ok(Some(match s.trim() {
            "off" | "none" | "never" => return Ok(None),
            "hourly" => Self::Hourly,
            "daily" => Self::Daily,
            "weekly" => Self::Weekly,
            other if !other.is_empty() && !other.contains(['\n', '\r']) => {
                Self::Calendar(other.to_owned())
            }
            other => return Err(UnitError::BadSchedule(other.to_owned())),
        }))
    }

    /// The `OnCalendar=` value. The fixed ones run at night, when servers are emptiest.
    pub fn on_calendar(&self) -> &str {
        match self {
            Self::Hourly => "hourly",
            Self::Daily => "*-*-* 04:00",
            Self::Weekly => "Mon *-*-* 04:00",
            Self::Calendar(c) => c,
        }
    }
}

/// The unit stem for a server: `hopper-<name>`, from the directory name unless given.
pub fn unit_stem(name: &str) -> Result<String, UnitError> {
    let cleaned: String = name
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '-' || c == '_' {
                c.to_ascii_lowercase()
            } else {
                '-'
            }
        })
        .collect();
    let cleaned = cleaned.trim_matches('-');
    if cleaned.is_empty() || cleaned.len() > 64 {
        return Err(UnitError::BadName(name.to_owned()));
    }
    Ok(format!("hopper-{cleaned}"))
}

/// What the units are rendered from.
#[derive(Debug, Clone)]
pub struct ServerUnits<'a> {
    /// `hopper-<name>`.
    pub stem: &'a str,
    /// Shown in `systemctl status`.
    pub title: &'a str,
    pub dir: &'a Path,
    /// The hopper binary the update unit runs.
    pub hopper: &'a Path,
}

impl ServerUnits<'_> {
    pub fn service_name(&self) -> String {
        format!("{}.service", self.stem)
    }

    pub fn update_service_name(&self) -> String {
        format!("{}-update.service", self.stem)
    }

    pub fn timer_name(&self) -> String {
        format!("{}-update.timer", self.stem)
    }

    pub fn server_service(&self) -> Result<String, UnitError> {
        let dir = setting_path(self.dir)?;
        let start = exec_path(&self.dir.join("start.sh"))?;
        let hopper = exec_path(self.hopper)?;
        let quoted_dir = exec_path(self.dir)?;
        let title = one_line(self.title);
        Ok(format!(
            "# Generated by hopper (`hopper service install`). Re-running that command\n\
             # rewrites this file; `hopper service remove` deletes it.\n\
             [Unit]\n\
             Description=Minecraft server: {title}\n\
             After=network-online.target\n\
             Wants=network-online.target\n\
             # A server that keeps crashing should stop, not restart forever.\n\
             StartLimitIntervalSec=600\n\
             StartLimitBurst=5\n\
             \n\
             [Service]\n\
             Type=simple\n\
             WorkingDirectory={dir}\n\
             ExecStart={start}\n\
             # Stop the way an operator would: `stop` over RCON, then wait for the server to\n\
             # finish saving and exit. If RCON is unreachable, systemd falls back to SIGTERM,\n\
             # which also saves, just less dependably.\n\
             ExecStop={hopper} service stop-server --dir {quoted_dir} --pid $MAINPID\n\
             KillSignal=SIGTERM\n\
             TimeoutStopSec=180\n\
             # The JVM exits 143 after a SIGTERM-initiated shutdown, which is a clean stop.\n\
             SuccessExitStatus=143\n\
             Restart=on-failure\n\
             RestartSec=15\n\
             \n\
             [Install]\n\
             WantedBy=default.target\n"
        ))
    }

    pub fn update_service(&self) -> Result<String, UnitError> {
        let hopper = exec_path(self.hopper)?;
        let dir = exec_path(self.dir)?;
        let title = one_line(self.title);
        Ok(format!(
            "# Generated by hopper (`hopper service install --update ...`).\n\
             [Unit]\n\
             Description=Update Minecraft server: {title}\n\
             After=network-online.target\n\
             Wants=network-online.target\n\
             \n\
             [Service]\n\
             Type=oneshot\n\
             # CURSEFORGE_API_KEY for CurseForge packs, if hopper stored one there.\n\
             EnvironmentFile=-%h/.config/hopper/env\n\
             ExecStart={hopper} service run-update --dir {dir} --unit {unit}\n",
            unit = self.service_name(),
        ))
    }

    pub fn update_timer(&self, schedule: &Schedule) -> String {
        format!(
            "# Generated by hopper (`hopper service install --update ...`).\n\
             [Unit]\n\
             Description=Check for pack updates: {title}\n\
             \n\
             [Timer]\n\
             OnCalendar={cal}\n\
             # Catch up after the machine was off at the scheduled time.\n\
             Persistent=true\n\
             RandomizedDelaySec=15min\n\
             \n\
             [Install]\n\
             WantedBy=timers.target\n",
            title = one_line(self.title),
            cal = schedule.on_calendar(),
        )
    }
}

fn checked(path: &Path) -> Result<String, UnitError> {
    let s = path.to_string_lossy().into_owned();
    if s.chars().any(char::is_control) {
        return Err(UnitError::UnsafePath(s));
    }
    Ok(s)
}

/// A path as a plain setting value, where only `%` specifiers are special.
fn setting_path(path: &Path) -> Result<String, UnitError> {
    Ok(checked(path)?.replace('%', "%%"))
}

/// A path as one `ExecStart=` word: quoted, with `\`, `"`, `$` and `%` escaped.
fn exec_path(path: &Path) -> Result<String, UnitError> {
    let s = checked(path)?
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('$', "$$")
        .replace('%', "%%");
    Ok(format!("\"{s}\""))
}

/// Free text for `Description=`: one line, specifiers neutralised.
fn one_line(s: &str) -> String {
    s.chars()
        .map(|c| if c.is_control() { ' ' } else { c })
        .collect::<String>()
        .replace('%', "%%")
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn units<'a>(dir: &'a Path, hopper: &'a Path) -> ServerUnits<'a> {
        ServerUnits {
            stem: "hopper-dc",
            title: "DeceasedCraft",
            dir,
            hopper,
        }
    }

    #[test]
    fn stems_are_safe_unit_names() {
        assert_eq!(
            unit_stem("DeceasedCraft Server").unwrap(),
            "hopper-deceasedcraft-server"
        );
        assert_eq!(unit_stem("dc").unwrap(), "hopper-dc");
        assert!(unit_stem("...").is_err());
        assert!(unit_stem("").is_err());
    }

    #[test]
    fn the_server_unit_starts_the_script_and_stops_gracefully() {
        let dir = PathBuf::from("/srv/mc/dc");
        let hopper = PathBuf::from("/home/u/.local/bin/hopper");
        let unit = units(&dir, &hopper).server_service().unwrap();
        assert!(unit.contains("WorkingDirectory=/srv/mc/dc\n"));
        assert!(unit.contains("ExecStart=\"/srv/mc/dc/start.sh\"\n"));
        assert!(unit.contains("KillSignal=SIGTERM\n"));
        assert!(unit.contains(
            "ExecStop=\"/home/u/.local/bin/hopper\" service stop-server --dir \"/srv/mc/dc\" --pid $MAINPID\n"
        ));
        assert!(unit.contains("SuccessExitStatus=143\n"));
        assert!(unit.contains("WantedBy=default.target\n"));
    }

    #[test]
    fn awkward_paths_are_escaped_for_systemd() {
        let dir = PathBuf::from("/srv/my \"100%\" $erver");
        let hopper = PathBuf::from("/bin/hopper");
        let u = units(&dir, &hopper);
        let unit = u.server_service().unwrap();
        assert!(
            unit.contains("WorkingDirectory=/srv/my \"100%%\" $erver\n"),
            "{unit}"
        );
        assert!(
            unit.contains(r#"ExecStart="/srv/my \"100%%\" $$erver/start.sh""#),
            "{unit}"
        );
        let update = u.update_service().unwrap();
        assert!(
            update.contains(r#"--dir "/srv/my \"100%%\" $$erver""#),
            "{update}"
        );
    }

    #[test]
    fn control_characters_in_paths_are_refused() {
        let dir = PathBuf::from("/srv/a\nExecStartPre=/bin/evil");
        let hopper = PathBuf::from("/bin/hopper");
        assert!(units(&dir, &hopper).server_service().is_err());
        assert!(units(&dir, &hopper).update_service().is_err());
    }

    #[test]
    fn the_update_unit_runs_hopper_against_the_server() {
        let dir = PathBuf::from("/srv/dc");
        let hopper = PathBuf::from("/home/u/.local/bin/hopper");
        let unit = units(&dir, &hopper).update_service().unwrap();
        assert!(unit.contains(
            "ExecStart=\"/home/u/.local/bin/hopper\" service run-update --dir \"/srv/dc\" --unit hopper-dc.service\n"
        ));
        assert!(unit.contains("Type=oneshot"));
    }

    #[test]
    fn schedules_parse() {
        assert_eq!(Schedule::parse("off").unwrap(), None);
        assert_eq!(Schedule::parse("daily").unwrap(), Some(Schedule::Daily));
        assert_eq!(
            Schedule::parse("Sat *-*-* 05:30").unwrap(),
            Some(Schedule::Calendar("Sat *-*-* 05:30".into()))
        );
        assert!(Schedule::parse("").is_err());
        let dir = PathBuf::from("/srv/dc");
        let timer = units(&dir, &dir).update_timer(&Schedule::Weekly);
        assert!(timer.contains("OnCalendar=Mon *-*-* 04:00\n"));
        assert!(timer.contains("Persistent=true\n"));
    }
}
