[package]
name = "hopper-mc"
description = "Install and update Minecraft server modpacks from Modrinth and CurseForge."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hopper"
path = "src/main.rs"

[dependencies]
hopper-core = { path = "../hopper-core", version = "0.1.5" }
clap.workspace = true
clap_complete.workspace = true
anyhow.workspace = true
tokio.workspace = true
url.workspace = true
serde.workspace = true

[dev-dependencies]
tempfile = "3"
zip.workspace = true
serde_json.workspace = true
