[package]
name = "hopper-mc"
description = "Manage Minecraft modpack servers from Modrinth, CurseForge and GTNH under systemd."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hopper"
path = "src/main.rs"

[dependencies]
hopper-core = { path = "../hopper-core", version = "0.3.0" }
clap.workspace = true
clap_complete.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["net"] }
url.workspace = true
serde.workspace = true
serde_json.workspace = true
tar.workspace = true
flate2.workspace = true
zip.workspace = true
libc = "0.2"

[dev-dependencies]
tempfile = "3"
zip.workspace = true
serde_json.workspace = true
